// Hebrew text-to-speech via the Web Speech API (system voices, works offline).

let voices: SpeechSynthesisVoice[] = []

function refreshVoices(): void {
  voices = window.speechSynthesis.getVoices()
}

export function initSpeech(): void {
  if (typeof window === 'undefined' || !('speechSynthesis' in window)) return
  refreshVoices()
  window.speechSynthesis.onvoiceschanged = refreshVoices
}

function hebrewVoice(): SpeechSynthesisVoice | null {
  return voices.find((v) => v.lang.toLowerCase().startsWith('he')) ?? null
}

export function canSpeakHebrew(): boolean {
  return typeof window !== 'undefined' && 'speechSynthesis' in window && hebrewVoice() !== null
}

/**
 * Unvocalized Hebrew is ambiguous; the system voice sometimes picks the wrong
 * reading. Manual overrides are the final authority — they win over the
 * generated vocalization data. Extend as more misreadings are found.
 */
const PRONUNCIATION_OVERRIDES: Record<string, string> = {
  'דוד': 'דּוֹד', // uncle (dod) — otherwise read as the name David
  'דודה': 'דּוֹדָה', // aunt (doda)
  // the voice flattens tsere-yud to plain 'e'; an explicit shva on the yud
  // makes it a closing glide: ei-lu (double-yud read as an extra syllable)
  'אילו': 'אֵיְלוּ', // which (pl.) — ei-lu, not e-lu / e-ai-lu
}

export interface VocalizedMap {
  /** cleaned full string -> fully vocalized string */
  full: Record<string, string>
  /** single token -> vocalized token */
  tokens: Record<string, string>
}

// generated by scripts/vocalize.mjs (Dicta Nakdan + Sanch's own vocabulary
// nikud); injected at startup so this module stays importable in tests
let vocalized: VocalizedMap = { full: {}, tokens: {} }

export function loadVocalized(map: VocalizedMap): void {
  vocalized = map
}

/**
 * Prepares dictionary entries for speech: "עובד/עובדת (ב)" is written for the eye,
 * not the voice. Parenthesized grammar hints are dropped, slash-separated forms
 * become comma pauses, then the text is vowelized (full-phrase match first,
 * per-token second, manual overrides always winning).
 */
export function ttsNormalize(text: string): string {
  const cleaned = text
    .replace(/\([^)]*\)/g, ' ')
    .replace(/\s*\/\s*/g, ', ')
    .replace(/\s+/g, ' ')
    .replace(/\s*,\s*$/g, '')
    .trim()
  const vocalizeToken = (token: string) => {
    // trailing punctuation (?, ., !, comma…) is not part of the word
    const m = token.match(/^(.*?)([,?.!:;]*)$/)!
    const word = PRONUNCIATION_OVERRIDES[m[1]] ?? vocalized.tokens[m[1]] ?? m[1]
    return word + m[2]
  }
  const hasManualOverride = cleaned.split(/[\s,]+/).some((t) => PRONUNCIATION_OVERRIDES[t])
  if (!hasManualOverride && vocalized.full[cleaned]) return vocalized.full[cleaned]
  return cleaned.split(' ').map(vocalizeToken).join(' ')
}

export function speakHebrew(text: string): boolean {
  if (typeof window === 'undefined' || !('speechSynthesis' in window)) return false
  const utterance = new SpeechSynthesisUtterance(ttsNormalize(text))
  const voice = hebrewVoice()
  if (voice) utterance.voice = voice
  utterance.lang = 'he-IL'
  utterance.rate = 0.85
  window.speechSynthesis.cancel()
  window.speechSynthesis.speak(utterance)
  return true
}
