// Hebrew text-to-speech via the Web Speech API (system voices, works offline).

let voices: SpeechSynthesisVoice[] = []

function refreshVoices(): void {
  voices = window.speechSynthesis.getVoices()
}

export function initSpeech(): void {
  if (typeof window === 'undefined' || !('speechSynthesis' in window)) return
  refreshVoices()
  window.speechSynthesis.onvoiceschanged = refreshVoices
}

// BCP-47 lang of the word being learned in the active course. The speak/can-speak
// helpers keep their `Hebrew` names for call-site stability, but dispatch on this:
// Hebrew goes through the nikud pipeline, other languages speak their text as-is.
let currentLang = 'he-IL'

export function setSpeechLang(lang: string): void {
  currentLang = lang
}

function langPrefix(): string {
  return currentLang.slice(0, 2).toLowerCase()
}

function currentVoice(): SpeechSynthesisVoice | null {
  const p = langPrefix()
  return voices.find((v) => v.lang.toLowerCase().startsWith(p)) ?? null
}

// True when the active course's language can be spoken by an installed voice.
export function canSpeakHebrew(): boolean {
  return typeof window !== 'undefined' && 'speechSynthesis' in window && currentVoice() !== null
}

/**
 * Unvocalized Hebrew is ambiguous; the system voice sometimes picks the wrong
 * reading. Manual overrides are the final authority — they win over the
 * generated vocalization data. Extend as more misreadings are found.
 */
export const PRONUNCIATION_OVERRIDES: Record<string, string> = {
  'דוד': 'דּוֹד', // uncle (dod) — otherwise read as the name David
  'דודה': 'דּוֹדָה', // aunt (doda)
  'מכתב': 'מִכְתָּב', // letter (mikhtav) — Dicta picked מַכְתֵּב (dictation machine)
  'סבא': 'סַאבָּא', // grandpa — mater-lectionis aleph pulls the stress to SA-ba (measured)
  'סבתא': 'סַבְּתָא', // grandma — the only spelling Carmit renders differently (SAV-ta)
  'כמה': 'כַּאמָּה', // KA-ma (how much/how old) — reported in בת כמה את
  // bayit family: plain nikud — Sanch found the mater-aleph respelling (בַּאיִת)
  // worse than Carmit's default reading (2026-07-17); keep entries so הבית is
  // covered and no generated respelling can come back
  'בית': 'בַּיִת',
  'הבית': 'הַבַּיִת',
  'מהבית': 'מֵהַבַּיִת',
  'בבית': 'בַּבַּיִת',
  'גרמניה': 'גֶּרְמַנְיָה', // plain nikud beats the generated aleph respelling (same call)
  'מים': 'מַיְם', // water — closing glide reads as one stressed syllable: MA-im
  'שפה': 'שָׂפָה', // language (sa-FA) — Dicta picked שֶׁפֹּה ("that here")
  'צוהוריים': 'צָהֳרַיְם', // noon (tso-ho-RA-im) — no nikud data; closing glide like מים
  'היי': 'הַאי', // hi (hay) — one closed syllable (measured)
  'ו': 'וֶה', // the prefix "ve-" taught as a standalone entry ("ו...")
  'מ': 'מִ', // the prefix "mi-" — bare mem is read as the letter name (measured)
  'אנגליה': 'אַנְגְּלִיאָה', // England (ang-LI-ya) — mater aleph pulls stress (measured .32→.71)
  'מנגו': 'מַאנְגּוֹ', // mango (MAN-go) — mater aleph (measured .60→.68)
}

/**
 * Whole-phrase corrections checked before any token work. Needed when a
 * per-token override is wrong in a specific phrase: standalone בית is BA-yit,
 * but the construct בית ספר is "bet sefer" — the token pass would corrupt it.
 */
export const PHRASE_OVERRIDES: Record<string, string> = {
  'בית ספר': 'בֵּית סֵפֶר', // bet SE-fer, not BA-yit sefer
}

/**
 * The voice flattens tsere-yud (אֵי) into plain 'e'. An explicit shva on the
 * bare yud turns it into a closing glide: בֵּיצָה -> בֵּיְצָה (bei-tza),
 * אֵילוּ -> אֵיְלוּ (ei-lu). Applied to every vocalized word.
 */
export function forceEiGlide(text: string): string {
  // tsere (other marks of the same letter may follow it) + bare yud -> add shva
  return text.replace(
    /\u05B5([\u05B0-\u05BC\u05C1\u05C2\u05C7]*)\u05D9(?![\u05B0-\u05BC\u05C1\u05C2\u05C7])/g,
    '\u05B5$1\u05D9\u05B0',
  )
}

export interface VocalizedMap {
  /** cleaned full string -> fully vocalized string */
  full: Record<string, string>
  /** single token -> vocalized token */
  tokens: Record<string, string>
}

// generated by scripts/vocalize.mjs (Dicta Nakdan + Sanch's own vocabulary
// nikud); injected at startup so this module stays importable in tests
let vocalized: VocalizedMap = { full: {}, tokens: {} }

export function loadVocalized(map: VocalizedMap): void {
  vocalized = map
}

// measured stress respellings generated by scripts/fix-stress.mjs
let stressOverrides: Record<string, string> = {}

export function loadStressOverrides(map: Record<string, string>): void {
  stressOverrides = map
}

const NIKUD_RE = /[\u0591-\u05C7]/g
const stripNikud = (s: string) => s.replace(NIKUD_RE, '')

/**
 * Prepares dictionary entries for speech: "עובד/עובדת (ב)" is written for the eye,
 * not the voice. Parenthesized grammar hints are dropped, slash-separated forms
 * become period pauses (a comma pause was too short and the transition audible —
 * Sanch, 2026-07-17), then the text is vowelized (full-phrase match first,
 * per-token second, manual overrides always winning).
 */
export function ttsNormalize(text: string): string {
  const cleaned = text
    .replace(/\([^)]*\)/g, ' ')
    .replace(/\s*\/\s*/g, '. ')
    .replace(/\s+/g, ' ')
    .replace(/\s*,\s*$/g, '')
    .trim()
  const phrase = PHRASE_OVERRIDES[cleaned]
  if (phrase) return forceEiGlide(phrase)
  const vocalizeToken = (token: string) => {
    // trailing punctuation (?, ., !, comma…) is not part of the word
    const m = token.match(/^(.*?)([,?.!:;]*)$/)!
    return (vocalized.tokens[m[1]] ?? m[1]) + m[2]
  }
  // vocalized.full is keyed with ", " separators (built before the period-pause
  // change); slash entries must still hit it — the token fallback can pick the
  // wrong homograph (אַתְּ vs אֶת)
  const legacyFull = cleaned.includes('. ')
    ? vocalized.full[cleaned.replace(/\. /g, ', ')]?.replace(/, /g, '. ')
    : undefined
  const base =
    vocalized.full[cleaned] ?? legacyFull ?? cleaned.split(' ').map(vocalizeToken).join(' ')
  // post-pass: manual corrections and measured stress respellings win,
  // matched by consonant skeleton so they also apply inside full sentences
  const out = base
    .split(' ')
    .map((token) => {
      const m = token.match(/^(.*?)([,?.!:;]*)$/)!
      const skeleton = stripNikud(m[1])
      const repl = PRONUNCIATION_OVERRIDES[skeleton] ?? stressOverrides[skeleton]
      return (repl ?? m[1]) + m[2]
    })
    .join(' ')
  return forceEiGlide(out)
}

// For non-Hebrew courses the text is a plain word/phrase written for the eye:
// drop parenthetical grammar hints and turn slash-separated forms into pauses.
function plainNormalize(text: string): string {
  return text
    .replace(/\([^)]*\)/g, ' ')
    .replace(/\s*\/\s*/g, ', ')
    .replace(/\s+/g, ' ')
    .replace(/\s*,\s*$/g, '')
    .trim()
}

/** Speak arbitrary text in a given language (e.g. an English translation),
 * independent of the active course language. */
export function speakText(text: string, lang: string, onEnd?: () => void): boolean {
  if (typeof window === 'undefined' || !('speechSynthesis' in window)) {
    onEnd?.()
    return false
  }
  const utterance = new SpeechSynthesisUtterance(plainNormalize(text))
  if (onEnd) {
    let called = false
    const done = () => {
      if (!called) {
        called = true
        onEnd()
      }
    }
    utterance.onend = done
    utterance.onerror = done
    window.setTimeout(done, 12000) // safety: never hang the flow
  }
  const p = lang.slice(0, 2).toLowerCase()
  const voice = voices.find((v) => v.lang.toLowerCase().startsWith(p)) ?? null
  if (voice) utterance.voice = voice
  utterance.lang = lang
  utterance.rate = 0.9
  window.speechSynthesis.cancel()
  window.speechSynthesis.speak(utterance)
  return true
}

export function speakHebrew(text: string, onEnd?: () => void): boolean {
  if (typeof window === 'undefined' || !('speechSynthesis' in window)) {
    onEnd?.()
    return false
  }
  const hebrew = langPrefix() === 'he'
  const utterance = new SpeechSynthesisUtterance(hebrew ? ttsNormalize(text) : plainNormalize(text))
  if (onEnd) {
    let called = false
    const done = () => {
      if (!called) {
        called = true
        onEnd()
      }
    }
    utterance.onend = done
    utterance.onerror = done
    window.setTimeout(done, 12000) // safety: never hang the flow
  }
  const voice = currentVoice()
  if (voice) utterance.voice = voice
  utterance.lang = currentLang
  utterance.rate = hebrew ? 0.85 : 0.9
  window.speechSynthesis.cancel()
  window.speechSynthesis.speak(utterance)
  return true
}
