// Hebrew text-to-speech via the Web Speech API (system voices, works offline).

let voices: SpeechSynthesisVoice[] = []

function refreshVoices(): void {
  voices = window.speechSynthesis.getVoices()
}

export function initSpeech(): void {
  if (typeof window === 'undefined' || !('speechSynthesis' in window)) return
  refreshVoices()
  window.speechSynthesis.onvoiceschanged = refreshVoices
}

function hebrewVoice(): SpeechSynthesisVoice | null {
  return voices.find((v) => v.lang.toLowerCase().startsWith('he')) ?? null
}

export function canSpeakHebrew(): boolean {
  return typeof window !== 'undefined' && 'speechSynthesis' in window && hebrewVoice() !== null
}

/**
 * Unvocalized Hebrew is ambiguous; the system voice sometimes picks the wrong
 * reading. Manual overrides are the final authority — they win over the
 * generated vocalization data. Extend as more misreadings are found.
 */
export const PRONUNCIATION_OVERRIDES: Record<string, string> = {
  'דוד': 'דּוֹד', // uncle (dod) — otherwise read as the name David
  'דודה': 'דּוֹדָה', // aunt (doda)
  'מכתב': 'מִכְתָּב', // letter (mikhtav) — Dicta picked מַכְתֵּב (dictation machine)
  'סבא': 'סַאבָּא', // grandpa — mater-lectionis aleph pulls the stress to SA-ba (measured)
  'סבתא': 'סַבְּתָא', // grandma — the only spelling Carmit renders differently (SAV-ta)
  'כמה': 'כַּאמָּה', // KA-ma (how much/how old) — reported in בת כמה את
  // bayit family: mater-lectionis aleph forces BA-yit (measured 19/7 head-heavy)
  'בית': 'בַּאיִת',
  'הבית': 'הַבַּאיִת',
  'מהבית': 'מֵהַבַּאיִת',
  'בבית': 'בַּבַּאיִת',
  'מים': 'מַיְם', // water — closing glide reads as one stressed syllable: MA-im
}

/**
 * The voice flattens tsere-yud (אֵי) into plain 'e'. An explicit shva on the
 * bare yud turns it into a closing glide: בֵּיצָה -> בֵּיְצָה (bei-tza),
 * אֵילוּ -> אֵיְלוּ (ei-lu). Applied to every vocalized word.
 */
export function forceEiGlide(text: string): string {
  // tsere (other marks of the same letter may follow it) + bare yud -> add shva
  return text.replace(
    /\u05B5([\u05B0-\u05BC\u05C1\u05C2\u05C7]*)\u05D9(?![\u05B0-\u05BC\u05C1\u05C2\u05C7])/g,
    '\u05B5$1\u05D9\u05B0',
  )
}

export interface VocalizedMap {
  /** cleaned full string -> fully vocalized string */
  full: Record<string, string>
  /** single token -> vocalized token */
  tokens: Record<string, string>
}

// generated by scripts/vocalize.mjs (Dicta Nakdan + Sanch's own vocabulary
// nikud); injected at startup so this module stays importable in tests
let vocalized: VocalizedMap = { full: {}, tokens: {} }

export function loadVocalized(map: VocalizedMap): void {
  vocalized = map
}

// measured stress respellings generated by scripts/fix-stress.mjs
let stressOverrides: Record<string, string> = {}

export function loadStressOverrides(map: Record<string, string>): void {
  stressOverrides = map
}

const NIKUD_RE = /[\u0591-\u05C7]/g
const stripNikud = (s: string) => s.replace(NIKUD_RE, '')

/**
 * Prepares dictionary entries for speech: "עובד/עובדת (ב)" is written for the eye,
 * not the voice. Parenthesized grammar hints are dropped, slash-separated forms
 * become comma pauses, then the text is vowelized (full-phrase match first,
 * per-token second, manual overrides always winning).
 */
export function ttsNormalize(text: string): string {
  const cleaned = text
    .replace(/\([^)]*\)/g, ' ')
    .replace(/\s*\/\s*/g, ', ')
    .replace(/\s+/g, ' ')
    .replace(/\s*,\s*$/g, '')
    .trim()
  const vocalizeToken = (token: string) => {
    // trailing punctuation (?, ., !, comma…) is not part of the word
    const m = token.match(/^(.*?)([,?.!:;]*)$/)!
    return (vocalized.tokens[m[1]] ?? m[1]) + m[2]
  }
  const base = vocalized.full[cleaned] ?? cleaned.split(' ').map(vocalizeToken).join(' ')
  // post-pass: manual corrections and measured stress respellings win,
  // matched by consonant skeleton so they also apply inside full sentences
  const out = base
    .split(' ')
    .map((token) => {
      const m = token.match(/^(.*?)([,?.!:;]*)$/)!
      const skeleton = stripNikud(m[1])
      const repl = PRONUNCIATION_OVERRIDES[skeleton] ?? stressOverrides[skeleton]
      return (repl ?? m[1]) + m[2]
    })
    .join(' ')
  return forceEiGlide(out)
}

export function speakHebrew(text: string, onEnd?: () => void): boolean {
  if (typeof window === 'undefined' || !('speechSynthesis' in window)) {
    onEnd?.()
    return false
  }
  const utterance = new SpeechSynthesisUtterance(ttsNormalize(text))
  if (onEnd) {
    let called = false
    const done = () => {
      if (!called) {
        called = true
        onEnd()
      }
    }
    utterance.onend = done
    utterance.onerror = done
    window.setTimeout(done, 12000) // safety: never hang the flow
  }
  const voice = hebrewVoice()
  if (voice) utterance.voice = voice
  utterance.lang = 'he-IL'
  utterance.rate = 0.85
  window.speechSynthesis.cancel()
  window.speechSynthesis.speak(utterance)
  return true
}
